language: node_js
os: osx
cache: npm
node_js:
  - 12
  - node

before_script:
  - echo starting build
  - cd frontend
  - rm package-lock.json
  - npm install -g firebase-tools
  - npm install

script:
  - npm run-script build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
