language: node_js
cache: npm
node_js:
  - "12"
  - node

before_script:
  - echo starting build
  - cd frontend
  - npm install -g firebase-tools
  - npm install

script:
  - npm run-script build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
